version: '3.3'

services:
  landing-service:
    build: ./landing
    hostname: landing-service
    ports:
      - 5050:5050
    networks:
      sample:
        aliases:
          - landing-service
          
  addition-service:
    build: ./landing/app/add
    hostname: addition-service
    ports:
      - 5051:5051
    networks:
      sample:
        aliases:
          - addition-service

  subtraction-service:
    build: ./landing/app/sub
    hostname: subtraction-service
    ports:
      - 5052:5052
    networks:
      sample:
        aliases:
          - subtraction-service

  multiplication-service:
    build: ./landing/app/mul
    hostname: multiplication-service
    ports:
      - 5053:5053
    networks:
      sample:
        aliases:
          - multiplication-service

  division-service:
    build: ./landing/app/div
    hostname: division-service
    ports:
      - 5054:5054
    networks:
      sample:
        aliases:
          - division-service
        
  exponent-service:
    build: ./landing/app/exp
    hostname: exponent-service
    ports:
      - 5055:5055
    networks:
      sample:
        aliases:
          - exponent-service
        
  modulus-service:
    build: ./landing/app/mod
    hostname: modulus-service
    ports:
      - 5056:5056
    networks:
      sample:
        aliases:
          - modulus-service

  equals-service:
    build: ./landing/app/equ
    hostname: equals-service
    ports:
      - 5057:5057
    networks:
      sample:
        aliases:
          - equals-service

networks:
  sample:
